name: "FIXME annotate"
description: "Check code for specific terms (FIXME, WIP, etc.) and pass (with code annotations) if any are found."
author: "@rippleFCL"
branding:
  icon: "list"
  color: "orange"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.case-sensitive }}
    - ${{ inputs.severity }}
inputs:
  terms:
    description: "The pipe-delimited searchable terms to pass as a regex group to `git grep`."
    required: false
    default: "FIXME"
  case-sensitive:
    description: "Whether the searchable terms passed to `git grep` should be case-sensitive or not."
    required: false
    default: true
  severity:
    description: "The severity seen in the annotation"
    required: false
    default: "error"
