name: "Self-test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test-case-sensitive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          terms: "wip|fix|fixme"
          case-sensitive: true
        env:
          INVERT_ERROR: test

  test-case-insensitive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          terms: "wip|fix|fixme"
          case-sensitive: false
        env:
          INVERT_ERROR: true
  test-case-severity-incorrect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          terms: "wip|fix|fixme"
          case-sensitive: false
          severity: "warning"
        env:
          INVERT_ERROR: true
  test-case-severity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          terms: "wip|fix|fixme"
          case-sensitive: false
          severity: "WARNING"


